#!/bin/sh

ENABLED=yes
PROCS=xkeen-autoreload-vless
ARGS="run"
PREARGS=""
DESC="$PROCS"
PATH=/opt/sbin:/opt/bin:/sbin:/bin:/usr/sbin:/usr/bin

# The application reads /opt/etc/xkeen-autoreload-vless.env itself.
# Do not source the file as shell code: the subscription URL is user data.

. /opt/etc/init.d/rc.func
